// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(VizsgaContext))]
    partial class VizsgaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Szavak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Angol")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("angol");

                    b.Property<string>("Magyar")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("magyar");

                    b.Property<int?>("TemaId")
                        .HasColumnType("int")
                        .HasColumnName("temaId");

                    b.Property<DateTime?>("Timestamps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamps")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__szavak__3213E83F795ED440");

                    b.HasIndex("TemaId");

                    b.ToTable("szavak", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Temanev")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("temanev");

                    b.Property<DateTime?>("Timestamps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamps")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__tema__3213E83F4103CD26");

                    b.ToTable("tema", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Szavak", b =>
                {
                    b.HasOne("Backend.Models.Tema", "Tema")
                        .WithMany("Szavaks")
                        .HasForeignKey("TemaId")
                        .HasConstraintName("FK__szavak__temaId__286302EC");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Backend.Models.Tema", b =>
                {
                    b.Navigation("Szavaks");
                });
#pragma warning restore 612, 618
        }
    }
}
